sudo: required
language: python
python:
  - 3.7

services:
  - docker

branches:
  only:
    - master

before_install:
  - python --version
  - pip install -U pip
  - pip install -U importlib-metadata
  - pip install -U pytest

install:
 # - pip install . # install package + test dependencies
 # - curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .
 # - docker run --rm --privileged multiarch/qemu-user-static:register --reset
 # - docker build -t cwilko/mi-portfolio-mgr .

before_script:
  - python app.py &

script:
  - pytest # run tests
 # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 # - docker push cwilko/mi-portfolio-mgr
